services:
  db:
    image: postgres:15-alpine
    container_name: umbra-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: umbrachat
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
